=== alibaba/pont/packages/vscode-pont/configSchema.json
{
  "title": "JSON schema for rap2ts configuration files",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "definitions": {
    "originUrl": {
      "description": "the API documents data request URL",
      "type": "string"
    }
  },
  "properties": {
    "originType": {
      "description": "数据源类型",
      "type": "string",
      "default": "SwaggerV2",
      "enum": ["SwaggerV2", "SwaggerV3"]
    },
    "commonTemplatePath": {
      "description": "自定义模板文件路径",
      "type": "string"
    },
    "templatePath": {
      "description": "the code generator template, a ts file",
      "type": "string",
      "default": "./template"
    },
    "transformPath": {
      "description": "自定义标准数据源转化文件路径",
      "type": "string"
    },
    "fetchMethodPath": {
      "description": "自定义数据源请求文件路径",
      "type": "string"
    },
    "outDir": {
      "description": "the directory code generated to, a relative path to the config file",
      "type": "string",
      "default": "./services"
    },
    "originUrl": {
      "$ref": "#/definitions/originUrl"
    },
    "prettierConfig": {
      "type": "object",
      "properties": {}
    },
    "usingMultipleOrigins": {
      "type": "boolean",
      "description": "是否开启多数据源模式"
    },
    "spiltApiLock": {
      "type": "boolean",
      "description": "是否拆分api-lock.json到具体数据源目录"
    },
    "usingOperationId": {
      "type": "boolean",
      "description": ""
    },
    "surrounding": {
      "type": "string",
      "description": "pont生成代码的运行环境（无需更改）",
      "enum": ["typeScript", "javaScript"]
    },
    "mocks": {
      "type": "object",
      "description": "自动化mock服务，mocks 数据可以在 .mocks/mocks.ts 下自定义编辑。",
      "properties": {
        "enable": {
          "type": "boolean",
          "default": true,
          "description": "是否开启"
        },
        "port": {
          "type": "number",
          "default": 8080,
          "description": "mock服务端口号"
        },
        "wrapper": {
          "type": "string",
          "description": "是否把接口返回的数据包在固定格式下, {response} 表示返回数据结构",
          "default": "{\"code\": 0, \"data\": {response}, \"message\": \"\"}"
        },
        "basePath": {
          "type": "string",
          "default": "",
          "description": "接口基础路径"
        }
      }
    },
    "templateType": {
      "type": "string",
      "description": "可选的内置模板",
      "enum": ["fetch", "hooks"]
    },
    "origins": {
      "type": "array",
      "description": "数据源列表",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "数据源名"
          },
          "originUrl": {
            "$ref": "#/definitions/originUrl"
          },
          "customTemplatePath": {
            "description": "自定义模板文件路径",
            "type": "string"
          },
          "originType": {
            "description": "数据源类型",
            "type": "string",
            "default": "SwaggerV2",
            "enum": ["SwaggerV2", "SwaggerV3"]
          }
        }
      }
    },
    "baiduTranslateConfigs": {
      "type": "array",
      "description": "百度翻译配置信息",
      "items": {
        "type": "object",
        "properties": {
          "appId": {
            "type": "string",
            "description": "百度翻译开放平台 - APP ID"
          },
          "appSecret": {
            "type": "string",
            "description": "百度翻译开放平台 - 秘钥"
          }
        }
      }
    },
    "translatePath": {
      "description": "自定义翻译文件的生成路径,包含文件名（使用相对路径指定）",
      "type": "string"
    }
  }
}

=== alibaba/pont/packages/pont-core/__tests__/fixtures/config-multiple-origins.json
{
  "outDir": "../services",
  "templatePath": "./pontTemplate",
  "transformPath": "./transform",
  "origins": [
    {
      "originUrl": "http://127.0.0.1:9099/api-docs.json",
      "name": "api1"
    },
    {
      "originUrl": "http://127.0.0.1:9099/api-docs.json",
      "name": "api2"
    }
  ]
}
